### ISSUE TITLE
What is 'MY-GCLOUD-REFRESH-TOKEN' supposed to be?

### ISSUE THREAD

**Issue by turiphro** [vially/wercker-step-gcr-auth#1]
I guess it's related to OAuth. Client ID? Client secret? Some mash-up? API key? Service account key? Nothing seems to work, always returns:

```
2016/03/12 23:45:18 oauth2: cannot fetch token: 400 Bad Request
Response: {
    "error" : "invalid_grant"
}
```

**Comment by vially** [comment]
I don't know exactly how it's generated but you can find it by running: `gcloud auth print-refresh-token` (assuming you've installed and configured the gcloud SDK).
I'm not on my PC right now so I can't check but I think it's also stored in this file: `~/.config/gcloud/credentials.json`.

**Comment by turiphro** [comment]
Okay, found it, and seems to work. It feels a bit like a hack though, and not sure how long this token persists; I expected the normal issuing of new GCP OAuth or API tokens to be used. Might be something to clarify in the Readme.

**Comment by vially** [comment]
I agree that documentation could be improved but it is not very high on my priority list right now. I'm always open to pull requests though.
